# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Jira archive for Apache Lucene"
  homepage: https://lucene.apache.org/
  labels:
    - lucene

  enabled_merge_buttons:
    squash: true
    merge:  false
    rebase: false

  features:
    wiki: false
    issues: true
    projects: false

notifications:
  # commits:      commits@lucene.apache.org
  # issues:       issues@lucene.apache.org
  # pullrequests: issues@lucene.apache.org
  jira_options: link label worklog
