#!/bin/sh

cat <<_EOF >Crash.java
public class Crash {

  public static void main(String[] args) throws Throwable {
    new Crash().crash();
  }

  private Object alwaysNull;

  final void crash() throws Throwable {
    for (int r = 0; r < 3; r++) {
      for (int docNum = 0; docNum < 10000;) {
        if (r < 2) {
          for(int j=0;j<3000;j++)
            docNum++;
        } else {
          docNum++;
          doNothing(getNothing());
          if (alwaysNull != null) {
            throw new RuntimeException("BUG: checkAbort is always null: r=" + r + " of 3; docNum=" + docNum);
          }
        }
      }
    }
  }

  Object getNothing() {
    return this;
  }

  int x;
  void doNothing(Object o) {
    x++;
  }
}
_EOF

oldJH=$JAVA_HOME
runs=200
for f in /usr/java/*; do
	JAVA_HOME=$f
	export JAVA_HOME
	v=`$f/bin/java -fullversion 2>&1`
	if [ $? -ne 0 ]; then
		continue
	fi
	
	rm -f Crash.class
	$f/bin/javac Crash.java
	if [ -e Crash.class ]; then
		echo "$f ($v):"
			
		for o in "" "-server" "-client" "-Xbatch" "-Xint"; do 
			if $f/bin/java -version $o >/dev/null 2>&1; then
				fail=0
				for r in `seq 1 $runs`; do
					if $f/bin/java -cp . Crash >/dev/null 2>&1; then
						:;
					else
						fail=`expr $fail + 1`
					fi		
				done
	
				r="PASS"
				if [ $fail -gt 0 ]; then
					r="FAIL"
				fi
				echo "   $o: $fail/$runs failed: $r"
			fi
		done
	fi
done
JAVA_HOME=$oldJH
export JAVA_HOME
	 
